### ISSUE TITLE
example of deciding weather to sort by ASC or DESC

### ISSUE THREAD

**Issue by MarkRBM** [adrianhurt/play-api-rest-seed#4]
Thanks for the seed it is full of helpful ideas.  

So I see how you would get a list of tasks say and how you request the list to be sorted by "id", something like

`New Tasks.list(None, None, Some("id"), 1, 10)`

but how do I tell it to sort in Descending order? I see the code for this in the Task companion object but cant figure out how its utilised

**Comment by MarkRBM** [comment]
nvm figured it out, if anyone else comes across this see processSortByParam in ApiController.scala

**Comment by adrianhurt** [comment]
Hi @Ir1sh, I'm glad this seed is being useful for you. First of all, the intention is exactly that, giving ideas because each one codes in his own way. So adapt it as your needs and obviously there will be better ways to implement it. So let's see "my way":

In the readme you can see an example of sorting

```
/tasks?sort=-deadline,-date,order
```

As you can see the field sort is a simple string with a list of sorting fields separated by comma and each one can have a Descending order simply being prefixed by "-". So the sort answer for your question is to have the field `sort = Some("-id")`.

Then, as you can see, `Tasks.list` uses `ApiController. sortedPage` and `ApiController. processSortByParam` to take this string and transform it to a `Seq[(String, Boolean)]`, where each pair has the sorting field and a boolean indicating its order.

Finally, `Task.page` takes this `Seq` and transforms it to a sequence of sorting functions (using `Task.sortingFunc`).

**Comment by adrianhurt** [comment]
Oh, you found it!
